# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformTaskV4@4
  displayName: 'terrraform init'
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'aws-terraform23'
    backendAWSBucketName: 'azuredevops34343'
    backendAWSKey: 'tf/terraform.tfstate'
  
- task: TerraformTaskV4@4
  displayName: 'Terraform validate'
  inputs:
      provider: 'aws'
      command: 'validate'
    
- task: TerraformTaskV4@4
  displayName: 'Terraform plan'
  inputs:
      provider: 'aws'
      command: 'plan'
      environmentServiceNameAWS: 'aws-terraform23'
    
- task: TerraformTaskV4@4
  displayName: 'Terraform apply'
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws-terraform23'